spring:
  docker:
    compose:
      file: 'kafka-compose.yml'
      enabled: true
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 10
  application:
    name: kafka-toy

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 2147483647
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
